datasets:
  data_car:
    column_mapping:
      categorical_features:
        - location
        - branch
        - model
        - origin
        - external_color
        - internal_color
        - num_seats
        - fuels
        - gearbox
        - car_type
        - wheel_drive
      numerical_features:
        - year
        - km_driven
        - engine_capacity
      target: price
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
      - regression_performance
      - num_target_drift
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 50
